---
- name: add nodejs repo
  apt_repository: repo='ppa:chris-lea/node.js'

- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - libxml2-dev
    - libxslt1-dev
    - make
    - nodejs
    - python-dev
    - python-virtualenv
    - virtualenvwrapper
    - zlib1g-dev
  environment:
    LC_ALL: en_US.UTF-8

- name: install pip requirements
  pip: requirements=/vagrant/requirements.txt virtualenv=/vagrant/venv

- name: install pip development requirements
  pip: requirements=/vagrant/dev-requirements.txt virtualenv=/vagrant/venv

- name: install npm packages
  npm: name={{ item }} global=yes state=latest
  with_items:
    - gulp

- name: install local npm packages
  sudo_user: vagrant
  npm: path=/vagrant state=latest

- name: hide login message
  file: path=/home/vagrant/.hushlogin
        owner=vagrant
        group=vagrant
        mode=0644
        state=touch

- name: install bash_profile
  template: src=dot.bash_profile.j2
            dest=/home/vagrant/.bash_profile
            owner=vagrant
            group=vagrant
            mode=0644
