---
- hosts: dev
  become: yes
  roles:
    - role: ntp
      tags: ntp
    - role: vagrant
      tags: vagrant

- hosts: prod
  become: yes
  roles:
    - role: ntp
      tags: ntp
    - role: nginx
      tags: nginx
    - role: deploy
      tags: deploy
    - role: uwsgi
      tags: uwsgi
